In [ ]:
# numpy in python

# what is numpy?
# numpy is a library for the python programming language, adding support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

# numpy is a fundamental package for scientific computing with Python.
# numpy is open source and can be installed using pip.

In [3]:
# chck numpy version
import numpy as np
print(np.__version__)

2.2.4


In [4]:
# create a numpy array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [5]:
# create a 2 dimensional numpy array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# accessing elements in a numpy array
print(a[0])  # first element

print(a[1:4])  # elements from index 1 to 3
print(a[1:])  # elements from index 1 to end

1
[2 3 4]
[2 3 4 5]


In [9]:
# cerate a numpy array with zeros
c = np.zeros((3, 4))  # 3 rows and 4 columns
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# cerate a numpy random array
d = np.random.rand(3, 4)  # 3 rows and 4 columns
print(d)

[[0.71653257 0.37093186 0.59244181 0.31054208]
 [0.84984998 0.03974944 0.59032737 0.59799713]
 [0.59749003 0.08319192 0.54515006 0.06937287]]


In [13]:
# using int data type in random array
e = np.random.randint(1, 10, size=(3, 4))  # 3 rows and 4 columns
print(e)

[[3 1 3 2]
 [4 5 3 6]
 [2 6 9 7]]


In [14]:
# using numpy to create a range of numbers
f = np.arange(1, 10, 2)  # start, stop, step
print(f)

[1 3 5 7 9]


In [ ]:
# numpy use for mathematical operations
g = np.array([1, 2, 3])
h = np.array([4, 5, 6])
print(g + h)  # addition
print(g - h)  # subtraction
print(g * h)  # multiplication
print(g / h)  # division
print(g ** 2)  # power

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
