In [3]:
# Generate Random Integer

from numpy import random

# Generate a random integer between 0 and 10 (exclusive)
random_integer = random.randint(0, 10)
print(random_integer)

4


In [4]:
# Generate Random Float

float_number = random.rand()
print(float_number)

0.8782467046215124


In [18]:
# generate a random array of 5 random floats between 0 and 1
random_array = random.rand(5)
print(random_array)

# integer array of 5 random integers between 0 and 10 (exclusive)
random_integer_array = random.randint(0, 10, 5)
print(random_integer_array)

[0.74636339 0.72630671 0.62216628 0.74321004 0.01784324]
[6 1 6 8 5]


In [20]:
# generate 2d array of random integers between 0 and 10 (exclusive)
random_2d_array = random.randint(0, 10, (3, 3))
print(random_2d_array)

[[6 0 0]
 [0 9 7]
 [2 3 1]]


In [38]:
# Single Value using choice() method

random_choice = random.choice([1, 2, 3, 4, 5])
print(random_choice)

2


In [ ]:
# Array of Values using choice() method

random_choice_array = random.choice([1, 2, 3, 4, 5], size=(3, 3))
print(random_choice_array)

[[5 5 4]
 [4 4 4]
 [4 5 4]]


In [88]:
# Shuffling an Array USING shuffle() method

array_to_shuffle = [1, 2, 3, 4, 5]
random.shuffle(array_to_shuffle)
print(array_to_shuffle)


[2, 5, 1, 3, 4]


In [98]:
# Generating a Random Permutation
# what is a permutation?
# A permutation of a set is an arrangement of its members into a sequence or linear order.

# example of permutation

data = [1, 2, 3, 4, 5]
permutation = random.permutation(data)
print(permutation)

[4 1 5 2 3]
